services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    command: >
      sh -c "
        while ! pg_isready -h db -p 5432 -U farcapital_analytics; do
          echo 'Waiting for database...';
          sleep 1;
        done;
        echo 'Database is ready!';
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

  mage:
    build: .
    ports:
      - "6789:6789"
    volumes:
      - .:/app
    command: mage start .

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=farcapital_analytics
      - POSTGRES_USER=farcapital_analytics
      - POSTGRES_PASSWORD=passwordbrother
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U farcapital_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: