services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    command: python manage.py runserver 0.0.0.0:8000

  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

  mage:
    build: .
    ports:
      - "6789:6789"
    volumes:
      - .:/app
    command: mage start .