# Generated by Django 3.2.19 on 2024-08-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('registrations', models.IntegerField()),
                ('form_submissions', models.IntegerField()),
                ('landing_page_views', models.IntegerField()),
                ('bounce_rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Acquisition Metrics',
            },
        ),
        migrations.CreateModel(
            name='ActivationMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('event_type', models.CharField(max_length=50)),
                ('participants', models.IntegerField()),
                ('engagement_rate', models.FloatField()),
                ('completion_rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Activation Metrics',
            },
        ),
        migrations.CreateModel(
            name='AwarenessMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('platform', models.CharField(max_length=50)),
                ('impressions', models.IntegerField()),
                ('reach', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('video_views', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Awareness Metrics',
            },
        ),
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roi', models.FloatField()),
                ('awareness_impact', models.IntegerField()),
                ('acquisition_impact', models.IntegerField()),
                ('activation_impact', models.IntegerField()),
                ('retention_impact', models.FloatField()),
                ('referral_impact', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_id', models.CharField(max_length=100, unique=True)),
                ('first_touch_point', models.CharField(max_length=50)),
                ('last_touch_point', models.CharField(max_length=50)),
                ('total_touchpoints', models.IntegerField()),
                ('days_to_conversion', models.IntegerField(blank=True, null=True)),
                ('lifetime_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=50)),
                ('campaign_name', models.CharField(max_length=100)),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_audience', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('referral_source', models.CharField(max_length=100)),
                ('referrals', models.IntegerField()),
                ('conversion_rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Referral Metrics',
            },
        ),
        migrations.CreateModel(
            name='RetentionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=50)),
                ('active_users', models.IntegerField()),
                ('engagement_rate', models.FloatField()),
                ('churn_rate', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Retention Metrics',
            },
        ),
        migrations.CreateModel(
            name='RevenueMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('product_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source', models.CharField(max_length=50)),
                ('transactions', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Revenue Metrics',
            },
        ),
    ]
